import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Provider from "@/components/Helps/Provider";
import 'rsuite/dist/rsuite.min.css';
import { CustomProvider } from 'rsuite';
import DashboardMenu from "@/components/DashboardMenu/DashboardMenu.componets";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IdenStore | Dashboard",
  description: "Generated by create next app",
};


export default async function DashbortLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <Provider>
                    <CustomProvider>
                        <DashboardMenu/>
                        {children}
                        <Toaster
                            position="bottom-right"
                            reverseOrder={false}
                        />
                    </CustomProvider>
                </Provider>
            </body>
        </html>
    )
}
