import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Provider from "@/components/Helps/Provider";
import 'rsuite/dist/rsuite.min.css';
import "./globals.css";
import { CustomProvider } from 'rsuite';
import Nav from "@/components/Nav/Nav.components";


const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
      <Provider>
        <CustomProvider>
          {children}
        </CustomProvider>
      </Provider>
      </body>
    </html>
  );
}
