import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Nav from "@/components/Nav/Nav.components";
import "../globals.css";
import { GlobalContextProvider } from "@/components/Helps/GlobalBasket";
import Footer from "@/components/Footer/Footer.components";


const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={montserrat.className}>
        <GlobalContextProvider>
          <Nav/>
          {children}
          <Footer/>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
